# This workflow is managed by gh actions-lock.
# SPDX-License-Identifier: MPL-2.0
name: ClusterFuzzLite batch fuzzing
on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

permissions:
  contents: read

jobs:
  Batch:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: rust
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: address
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 1800
          mode: batch
          sanitizer: address
